// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqbf9kkYI4xg1rtH8bNOGs33ZmSUbVkKY',
    appId: '1:816480739666:web:0f34561ebe6990e4cb1a8b',
    messagingSenderId: '816480739666',
    projectId: 'placement-connect-61be0',
    authDomain: 'placement-connect-61be0.firebaseapp.com',
    storageBucket: 'placement-connect-61be0.firebasestorage.app',
    measurementId: 'G-08B0G6HRP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GVfKwjt1Y5NRMCFQsH3N_1lCYDjSlr4',
    appId: '1:816480739666:android:ee532780f2d5aa8fcb1a8b',
    messagingSenderId: '816480739666',
    projectId: 'placement-connect-61be0',
    storageBucket: 'placement-connect-61be0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOa5B4VF8Umye8CuD28-2JUM6rbpnJazA',
    appId: '1:816480739666:ios:ebeda964b303ed47cb1a8b',
    messagingSenderId: '816480739666',
    projectId: 'placement-connect-61be0',
    storageBucket: 'placement-connect-61be0.firebasestorage.app',
    iosBundleId: 'com.placementconnect.placementConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOa5B4VF8Umye8CuD28-2JUM6rbpnJazA',
    appId: '1:816480739666:ios:ebeda964b303ed47cb1a8b',
    messagingSenderId: '816480739666',
    projectId: 'placement-connect-61be0',
    storageBucket: 'placement-connect-61be0.firebasestorage.app',
    iosBundleId: 'com.placementconnect.placementConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqbf9kkYI4xg1rtH8bNOGs33ZmSUbVkKY',
    appId: '1:816480739666:web:92cdb89916c1cba9cb1a8b',
    messagingSenderId: '816480739666',
    projectId: 'placement-connect-61be0',
    authDomain: 'placement-connect-61be0.firebaseapp.com',
    storageBucket: 'placement-connect-61be0.firebasestorage.app',
    measurementId: 'G-JX878MK6S3',
  );
}
